using System;
using System.Collections.Generic;

namespace ACE.Database
{
    static class CharacterNames
    {
        public static List<string> List = new List<string>
        {
            "Accidental MasterMind",
            "Axel",
            "All Hail The King",
            "Annihilator",
            "Absolute Badass",
            "Angry Bird",
            "Alpha Male",
            "Atomic Blaster",
            "Atom Man",
            "Angel Of Death",
            "Angelic Male",
            "Automatic Maniac",
            "Blizzard",
            "Blood Thirsty",
            "Badass Billy",
            "Blitz",
            "Blaster",
            "Buckshot",
            "Bear Awakened",
            "Clown Lover",
            "Cereal Killer",
            "Catastrophic Override",
            "Cosmic Boy",
            "Crazy Eight",
            "Cue Ball",
            "Darker Horse",
            "Death Dealer",
            "Desert Hawk",
            "Diamond Damage",
            "Death Digger",
            "Damnation Dalmation",
            "Egotistic Ballistic",
            "Ego Monster",
            "Edgy Cowboy",
            "Eye Shooter",
            "Easy Target",
            "Flash Card Fire",
            "Flash",
            "Flaming Flyer",
            "Fantastic Guy",
            "Frozen Explosion",
            "Fast Hand",
            "Fierce Person Shooter",
            "Gamer Gateway",
            "Global Takeover",
            "Grave Digger",
            "Gadget Man",
            "Heavenly Hero",
            "Hectic Slaughter",
            "Hayday Mayday",
            "Hell On Wheels",
            "Indiana Cojones",
            "Iconic Man",
            "Jigsaw",
            "Jester",
            "Joyride",
            "Jughead",
            "King Of All",
            "Kill Happy Game Man",
            "Kitchen Killer",
            "Lucky Lager",
            "Little Gamer",
            "Lexus Lover",
            "Lucifer In Person",
            "Madman At Large",
            "Mastermind",
            "Malicious Master",
            "Mental Case",
            "Midnight Rider",
            "Naturally Good",
            "Natural Gold",
            "Nighttime Warrior",
            "Old School Gamer",
            "Off With Their Head",
            "Override",
            "Papa Smurf",
            "Papa Gamer",
            "Pretty Eyed Badass",
            "Psycho",
            "Radioactive Radiation",
            "Rad Madman",
            "Ranger Danger",
            "Renegade",
            "Respawn Ultimate",
            "Scary Shooter",
            "Shadow Creature",
            "Sappy Sandman",
            "The Ultimate Man",
            "Toxic Plague",
            "Ultimate Gamer",
            "Ultimate Badassery",
            "Vexed Vortex",
            "Vicious Valentine",
            "Widowmaker",
            "Yesterdays Bad News",
            "Yodeling Gamer",
            "Zesty Killer",
            "Zen Dude",
            "Zig Zag",
            "Amazing Babe",
            "Asteroid",
            "Awesome Sauce",
            "Babelicious",
            "Barbie Girl",
            "Beastie Girl",
            "Blood Rain",
            "Cute Killer",
            "Cali Badass",
            "Captain Kitten",
            "Cool Chick",
            "Danger Eye",
            "Dandy Death Eater",
            "Dragoness",
            "Disaster Lady",
            "Dandelion",
            "Devil In Disguise",
            "Deadly Dork",
            "Electric Goddess",
            "Ever Warrior",
            "Ember Rose",
            "Exotic Gamer",
            "Freaky Game Girl",
            "Fancy",
            "Fist Fighter",
            "Fast Eye",
            "Ghost General",
            "Great Giant",
            "Gypsy Goddess",
            "Goddess Of Gaming",
            "Hipster Hellhound",
            "Hip Hop Gal",
            "Hellfire Hazard",
            "Hyper Spartan",
            "Indigo Moon",
            "Irish Lass",
            "Irksome Killer",
            "Invisible Slaughterer",
            "Impulsively Inspired",
            "Junebug",
            "Jelly Jester",
            "Jilly Bean",
            "Killswitch Enrage",
            "Kickstart Killah",
            "Kast Ironic",
            "Kill All Kings",
            "Kool Diva",
            "Luxurious Lady",
            "Lucky Lover",
            "Lava Lovely",
            "Lovely Destroyer",
            "Lioness",
            "Little Cobra",
            "Lucy Lucifer",
            "Luna",
            "Madwoman",
            "Maximum Overdrive",
            "Mad Witch",
            "Marbled Goodness",
            "Marigold Missile",
            "Midnight Rose",
            "Moon Magic",
            "Mystified Mischief",
            "Night Fighter",
            "New Moon",
            "Never Down",
            "Nasty Gal",
            "NYC Baby",
            "Official Badass",
            "Orions Girlfriend",
            "Peppermint Danger",
            "Pissed Off Patty",
            "Petunia Of Death",
            "Pretty Murderer",
            "Queen Of Hearts",
            "Queen Of Kills",
            "Racy Raider",
            "Rambunctious Flower",
            "Romantic Mess",
            "Rose Colored Missus",
            "Rude And Loud",
            "Saint Gamer",
            "Sad Sane Sally",
            "Sexy Shooter",
            "Sassy Rider",
            "Thunder Rush",
            "Tasty Ranger",
            "Trixie Toya",
            "Tulip Breeze",
            "Tough Chick",
            "Vicious Vixen",
            "Valley Girl",
            "Venus Lovechild",
            "Willow Weeper",
            "Winter Queen",
            "Winters Mistress",
            "Widow Of Death",
            "Wild Mystery",
            "Zesty Queen",
            "Zorra",
            "Pizza Pasta",
            "Bear Hugger",
            "Skullomania",
            "Duff McWhalen",
            "Metal Shark",
            "Ash Crimson",
            "Cyber Woo",
            "Marshall Law",
            "Henry Cooldown",
            "Lancelot Lakeknight",
            "Starkiller",
            "Dingo Egret",
            "Darkdeath Evilman",
            "Hot Coldman",
            "Pink Gold Peach",
            "Azul the Cerulean",
            "Jet Brody",
            "Dash Rendar",
            "Marcus Fenix",
            "Trevor McFur",
            "Rosco McQueen",
            "Master Chief",
            "Edge Maverick",
            "Vincent Valentine",
            "Cloud Strife",
            "Cream the Rabbit",
            "Mace Griffin",
            "BJ Blazkovicz",
            "Shoot Gunner",
            "Decoy Octopus",
            "Hans Clamp",
            "Jeffry McWild",
            "Wolf Hawkfield",
            "Rinoa Heartilly",
            "Sol Badguy",
            "Fox McCloud",
            "Ceaseless Discharge",
            "Dick Gumshoe",
            "Phoenix Wright",
            "Apollo Justice",
        };

        private static readonly Random rand = new Random();

        public static string GetRandom()
        {
            var index = rand.Next(List.Count);

            return List[index];
        }

        public static string GetRandomWithNumbers(int maxValue)
        {
            var numbers = rand.Next(maxValue);

            return $"{GetRandom()} {numbers}";
        }
    }
}
